### ISSUE TITLE
Sorting issues for certain fields

### ISSUE THREAD

**Issue by patrick-austin** [ral-facilities/datagateway#460] opened 2020-11-04 15:10 UTC
**Description**:
Have seen issues with the following fields when sorting, even when that field is populated:
- facilityCycle (ISIS):
  - Name: no effect on order in card/table
  - Description: no effect on order in card/table
- visit/investigation (DLS):
  - Beamline/Instrument: removes entries in card/table 
- investigation (ISIS):
  - instrument: removes entries in card/table

Has issues, but the field is unpopulated (so maybe we just don't handle empty fields properly when sorting?):
- investigation (ISIS):
  - DOI: removes entries in card/table
- investigation (Generic):
  - RB Number: removes entries in card/table
  - Instrument: removes entries in table view only
- dataset (Generic)
  - Datafile Count: removes entries, cardView only

Need to look into this more, work out what needs to be done.

**Acceptance criteria**:
- [ ] ?

**Comment by louise-davies** [comment] 2020-11-05 08:13
Sorting by instrument is an issue with the API that is being tracked via ral-facilities/datagateway-api#122

Sorting by datafileCount should be disabled as this is a calculated value (like size).

Facility cycles should work - we need to check this in the API, as well as the other ones.

**Comment by patrick-austin** [comment] 2020-12-09 12:49
Covered by ral-facilities/datagateway-api#122:
- [ ] Visit/investigation beamline/instrument
- [ ] ISIS investigation DOI: we're currently trying to get the DOI by `STUDYINVESTIGATION.STUDY.PID`, which gives no results and also doesn't sort. Could get it straight from the investigation (DOI is a field in ICAT schema for investigations) but if storing it on the study is more realistic I'll leave it as is

Will address:
- [ ] RB number in isn't a field in the ICAT schema, but is in our `app.types` interface, so attempting to sort by it always fails. I was under the impression RB was a different term for VISIT_ID (which we already display in the investigation table). Will disable sorting for now, but could also just remove RB from `app.types` (assuming that because it doesn't appear in the schema we'll never get a returned value for it)?
- [ ] Datafile count should be disabled in card view like it is in table view and DLS datasets

Can't diagnose:
- [ ] FacilityCycle name/description sends the requests to the API successfully (unlike the other issues where the request 500s), and can't see any reason why it would work for dates but not the name/description. We do join a lot of entities for the request, so maybe it's related to ral-facilities/datagateway-api#122 and won't be a problem when running against an API that's had that fix?

**Comment by sam-glendenning** [comment] 2021-06-03 14:03
Currently, a couple of issues are still known about. 

- SciGateway preprod - sorting by Instrument returns an Error 500
- ISIS dev and prod - sorting by Instrument returns an Error 400 (Cannot use one to many relationship in 'investigationInstruments.instrument.fullName' to order Investigation.)
- DLS dev and prod - sorting by Instrument returns an Error 500

The error 500s are believed to be because those sites are still making use of the DB backend of the API. This isn't a cause for concern and should eliminate this problem when the switch to python icat is made. Matthew is currently investigating the error 400s.

**Comment by louise-davies** [comment] 2021-06-03 14:06
@sam-glendenning @MRichards99 I presume the Instrument 400 error is the same as described on #714 so there's another example of trying to sort a related entity

**Comment by MRichards99** [comment] 2021-06-03 14:52
I can confirm the two 400s have the similar error messages, I've details to #714. The 400 found by Sam gives the following message, when the order filter is applied to the query:
`Cannot use one to many relationship in 'investigationInstruments.instrument.fullName' to order Investigation.`

Since that ISIS endpoint queries the investigation entity, I can't see another way to get to the instrument's full name without using a one to many relationship?

For ease, this is the request in question (I've been using ISIS dev):
`https://{datagateway-api}/instruments/1/facilitycycles/1/investigations?order="investigationInstruments.instrument.fullName desc"&order="id asc"&include=[{"investigationInstruments":"instrument"},{"studyInvestigations":"study"}]&skip=0&limit=50`

**Comment by MRichards99** [comment] 2021-06-24 15:34
This issue has been logged on Python ICAT's repo: https://github.com/icatproject/python-icat/issues/83

**Comment by louise-davies** [comment] 2021-07-08 13:16
Disable sorting on affected columns due to the python-icat issue being unable to be blocked

**Comment by MRichards99** [comment] 2021-07-14 09:37
> Disable sorting on affected columns due to the python-icat issue being unable to be blocked

@louise-davies we might not need to disable them after all as changes are going to be made in Python ICAT which I'll implement into DataGateway API. This will mean Python ICAT 0.19.0 will be needed on ISIS and Diamond.

**Comment by MRichards99** [comment] 2021-07-14 13:06
^ I've just realised that a newer version of Python ICAT won't actually be an issue for either ISIS or Diamond (beyond a typical redeployment), I was thinking of ICAT Server!

**Comment by sam-glendenning** [comment] 2021-07-19 10:32
@MRichards99 can you confirm the best course of action on this is to wait for ral-facilities/datagateway-api/issues/238 to be addressed and closed? As I understand it, this will allow for sorting on the mentioned columns to take place.

**Comment by MRichards99** [comment] 2021-07-19 11:39
@sam-glendenning correct, hopefully the new features from Python ICAT will work and won't have any unintended side effects. Once I've implemented https://github.com/ral-facilities/datagateway-api/issues/238, I'll test DataGateway on the specific sorting issues identified, have a play with some other views and watch the e2e tests in interactive mode to check for side effects.

**Comment by sam-glendenning** [comment] 2021-07-19 11:42
Noted, moving this to 'Blocked' for now

**Comment by sam-glendenning** [comment] 2021-07-22 13:16
Note for later: following further discussion, this issue is believed to be _fixed_ by ral-facilities/datagateway-api#238 but further testing is required to make sure once that PR is closed. Then this can be investigated and hopefully closed.

**Comment by sam-glendenning** [comment] 2021-07-23 15:12
As an update on this issue, the error 400s which were due to the API being unable to use a one-to-many relationship to link data together has been logged at ral-facilities/datagateway-api/issues/238 and is being addressed by ral-facilities/datagateway-api/pull/240. The other problem that caused the error 500s was because of the DB backend of the API still being used instead of the python_icat backend. However, when the switch to the python_icat backend was made, the issue did not go away (error 400, could not find attribute instrument). This was logged at ral-facilities/datagateway/issues/767 and the problem was found to be caused by an incorrect dataKey value for the column and an incorrect query which failed to fetch the investigationInstruments to link an investigation to an instrument. This issue is being fixed and addressed in ral-facilities/datagateway/pull/768.

**Comment by GoelBiju** [comment] 2021-07-27 12:58
> As an update on this issue, the error 400s which were due to the API being unable to use a one-to-many relationship to link data together has been logged at [ral-facilities/datagateway-api/issues/238](https://github.com/ral-facilities/datagateway-api/issues/238) and is being addressed by [ral-facilities/datagateway-api/pull/240](https://github.com/ral-facilities/datagateway-api/pull/240). The other problem that caused the error 500s was because of the DB backend of the API still being used instead of the python_icat backend. However, when the switch to the python_icat backend was made, the issue did not go away (error 400, could not find attribute `instrument`). This was logged at [/issues/767](https://github.com/ral-facilities/datagateway/issues/767) and the problem was found to be caused by an incorrect `dataKey` value for the column and an incorrect query which failed to fetch the investigationInstruments to link an investigation to an instrument. This issue is being fixed and addressed in [/pull/768](https://github.com/ral-facilities/datagateway/pull/768).

Since all issues have been addressed by PRs and these have been merged in, I am going to close this issue as suggested @MRichards99.

**Closed by GoelBiju** 2021-07-27 12:58 UTC
Labels: bug, datagateway-dataview
